server:
  port: 9000
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/user_DB
    username: postgres
    password: postgres
    hikari:
      maximum-pool-size: 10
      connection-timeout: 30000


  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
    hibernate:
      ddl-auto: none

management:
  endpoints:
    web:
      exposure:
        include: health,metrics
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true